export const formList = {
  general: {
    saved: false,
    isSubmit: true,
    firstName: '',
    lastName: '',
    country: '',
    state: '',
    zipcode: '',
    nationality: '',
    language: '',
    ssn: '',
    location: '',
    yearExp: '',
    dob: '',
    phoneNo: '',
    age: '',
    email: '',
    totalEvent: '',
    documents: [],
    faxAddress: '',
    mainOfficeAddress: '',
  },
  type: ['Male', 'Female', 'Other'],
  gender: ['Male', 'Female', 'Other'],
  rateLevel: [1, 2, 3, 4],
  eventType: ['Marriage', 'Birthday', 'Holycommunion'],

  localeByCountry: {
    IN: 'en-IN',
    US: 'en-US',
  },
  currencyByCountry: {
    IN: 'INR',
    US: 'USD',
  },
  menu: {
    saved: false,
    isSubmit: true,
    chkProfile: '',
    chkSummary: '',
    chkFocus: '',
    chkGallery: '',
    chkValue: '',
    chkAwards: '',
    chkTeam: '',
    chkContact: '',
    chkReport: '',
    chkGames: '',
    chkRank: '',
    chkBusiness: '',
    age: '',
    email: '',
    totalEvent: '',
    documents: [],
  },
  team: {
    saved: false,
    isSubmit: true,
    firstName: '',
    lastName: '',

    noExperiance: '',
    responsible: '',
    description: '',
    phoneNo: '',

    email: '',
    chkSocialmedia1: false,
    chkSocialmedia2: false,
    chkSocialmedia3: false,
    socialMedia: '',
    documents: [],
  },
  department: ['NGO', 'GOV', 'PWD'],
  focus: {
    saved: false,
    isSubmit: true,
    focusDescription: '',
    documents: [],
  },
  focusArea: ['Schools', 'Colleges', 'Job'],
  achievement: {
    saved: false,
    isSubmit: true,
    achiveDescription: '',
    documents: [],
  },
  achievements: ['Schools', 'Sports', 'Colleges', 'Job'],

  custcomment: {
    saved: false,
    isSubmit: true,
    firstName: '',
    lastName: '',
    custDescription: '',
    phoneEvent: '',

    custEmailid: '',
    documents: [],
  },
  clientEvent: ['Marriage', 'HolyCommunion', 'Colleges', 'School'],
  gallery: {
    saved: false,
    isSubmit: true,

    yearMonth: '',
    galleryDescription: '',
    documents: [],
  },
  gallerytype: ['Photos', 'Videos', 'Documents', 'PDF'],
  eventName: ['Marriage', 'Birthday', 'Engagement', 'Holy Feast'],
  schedule: {
    saved: false,
    isSubmit: true,
    person: '',
    scheduleDate: '',
    country: '',
    state: '',
    zipcode: '',
    nationality: '',
    language: '',

    address: '',
    county: '',
    city: '',

    scheduleDescription: '',
    documents: [],
  },
  scheduleType: ['Morning', 'Afternoon', 'Evening'],
  organization: ['NGO', 'PED', 'GOVT'],
  person: ['Org', 'Group', 'Private'],
  day: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  ],
  scheduleTime: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
  ],
};
