const Constants = {
  usa: [
    'Alaska',
    'Alabama',
    'Arkansas',
    'American Samoa',
    'Arizona',
    'California',
    'Colorado',
    'Connecticut',
    'District of Columbia',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Massachusetts',
    'Maryland',
    'Maine',
    'Michigan',
    'Minnesota',
    'Missouri',
    'Mississippi',
    'Montana',
    'North Carolina',
    'North Dakota',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Virgin Islands',
    'Vermont',
    'Washington',
    'Wisconsin',
    'West Virginia',
    'Wyoming',
  ],
  india: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Pondicherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Uttaranchal',
    'Uttar Pradesh',
    'West Bengal',
  ],
  phoneCode: { US: '+1', IN: '+91', PK: '+92' },
  user_empty_form: {
    firstName: '',
    lastName: '',
    dob: '',
    userName: '',
    password: '',
    password_re: '',
    country: '',
    state: '',
    address: '',
    city: '',
    zipCode: '',
    phone: '',
    phoneCode: '-',
    business: 'Individual',
    gender: '',
    minor: '',
    accssType: 2,
    approved: 'No',
    isSubmit: false,
    formChanges: -1,
    isLoading: false,
    message: 0,
  },
  nationality: [
    'British',
    'Afghan',
    'Albanian',
    'Algerian',
    'American',
    'Andorran',
    'Angolan',
    'Armenian',
    'Austrian',
    'Azerbaijani',
    'Argentinian',
    'Australian',
    'Bahraini',
    'Bangladeshi',
    'Barbadian',
    'Belarusian',
    'Belizean',
    'Beninese',
    'Bermudian',
    'Bhutanese',
    'Bolivian',
    'Bosnian',
    'Botswanan',
    'Bulgarian',
    'Burkinese',
    'Burundian',
    'Canadian',
    'Chinese',
    'Colombian',
    'Cuban',
    'Cambodian',
    'Cameroonian',
    'Cape Verdean',
    'Chadian',
    'Chilean',
    'Congolese',
    'Costa Rican',
    'Croat',
    'Cypriot',
    'Czech',
    'Danish',
    'Dominican',
    'Djiboutian',
    'Dominican',
    'Dutch',
    'Ecuadorean',
    'Egyptian',
    'Eritrean',
    'Estonian',
    'Ethiopian',
    'Fijian',
    'Finnish',
    'French Polynesian',
    'French',
    'Gabonese',
    'Gambian',
    'Georgian',
    'German',
    'Guatemalan',
    'Ghanaian',
    'Greek',
    'Grenadian',
    'Guinean',
    'Guyanese',
    'Haitian',
    'Honduran',
    'Hungarian',
    'Indian',
    'Ireland',
    'Israeli',
    'Italian',
    'Icelandic',
    'Indonesian',
    'Iranian',
    'Iraqi',
    'Japanese',
    'Jamaican',
    'Jordanian',
    'Kazakh',
    'Kenyan',
    'North Korean',
    'Kuwaiti',
    'Latvian',
    'Lebanese',
    'Liberian',
    'Libyan',
    'Lithuanian',
    'LUXEMBOURG',
    'Madagascan',
    'Malawian',
    'Malaysian',
    'Maldivian',
    'Malian',
    'Maltese',
    'Mauritanian',
    'Mauritian',
    'Monacan',
    'Mongolian',
    'Montenegrin',
    'Moroccan',
    'Mozambican',
    'Mexican',
    'Namibian',
    'Nepalese',
    'New Zealand',
    'Nicaraguan',
    'Nigerien',
    'Nigerian',
    'Norwegian',
    'Omani',
    'Pakistani',
    'Panamanian',
    'Guinean',
    'Paraguayan',
    'Peruvian',
    'Philippine',
    'Polish',
    'Portuguese',
    'Qatari',
    'Romanian',
    'Rwandan',
    'Salvadorean',
    'Samoan',
    'Saudi Arabian',
    'Senegalese',
    'Serbian',
    'Sierra Leonian',
    'Singaporean',
    'Slovak',
    'Slovenian',
    'Slomoni',
    'Somali',
    'South African',
    'South Korean',
    'Spanish',
    'Swedish',
    'Swiss',
    'Sri Lankan',
    'Sudanese',
    'Surinamese',
    'Swazi',
    'Taiwanese',
    'Tajik',
    'Thai',
    'Togolese',
    'Trinidadian',
    'Tunisian',
    'Turkish',
    'Turkoman',
    'Tuvaluan',
    'Ugandan',
    'Ukrainian',
    'Emirati',
    'Venezuelan',
    'Vietnamese',
    'Uruguayan',
    'Uzbek',
    'Vanuatuan',
    'Yemeni',
    'Zambian',
  ],
  langauges: [
    'Akan',
    'Amharic',
    'Arabic',
    'Assamese',
    'Awadhi',
    'Azerbaijani',
    'Balochi',
    'Belarusian',
    'Bengali',
    'Bhojpuri',
    'Burmese',
    'Chewa',
    'Chhattisgarhi',
    'Chittagonian',
    'Czech',
    'Deccan',
    'Dhundhari',
    'Dutch',
    'Eastern Min',
    'English',
    'French',
    'Fula',
    'German',
    'Greek',
    'Gujarati',
    'Haitian Creole',
    'Hakka',
    'Haryanvi',
    'Hausa',
    'Hiligaynon',
    'Hindi',
    'Hmong',
    'Hungarian',
    'Igbo',
    'Ilocano',
    'Italian',
    'Japanese',
    'Javanese',
    'Jin',
    'Kannada',
    'Kazakh',
    'Khmer',
    'Kinyarwanda',
    'Kirundi',
    'Konkani',
    'Korean',
    'Kurdish',
    'Madurese',
    'Magahi',
    'Maithili',
    'Malagasy',
    'Malay/Indonesian',
    'Malayalam',
    'Marathi',
    'Marwari',
    'Mossi',
    'Nepali',
    'Northern Min',
    'Odia(Oriya)',
    'Oromo',
    'Pashto',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Quechua',
    'Romanian',
    'Russian',
    'Saraiki',
    'Shona',
    'Sindhi',
    'Sinhalese',
    'Somali',
    'Southern Min',
    'Spanish',
    'Sundanese',
    'Swedish',
    'Sylheti',
    'Tagalog',
    'Tamil',
    'Telugu',
    'Thai',
    'Turkish',
    'Turkmen',
    'Ukrainian',
    'Urdu',
    'Uyghur',
    'Uzbek',
    'Vietnamese',
    'Xhosa',
    'Xiang (Hunnanese)',
    'Yoruba',
    'Yue (Cantonese)',
    'Zhuang',
    'Zulu',
  ],
  getAge: (date) => {
    if (!date) return '';
    const now = new Date();
    //const today = new Date(now.getYear(),now.getMonth(),now.getDate());

    const yearNow = now.getYear();
    const monthNow = now.getMonth();
    const dateNow = now.getDate();

    const dob = new Date(date);
    const yearDob = dob.getYear();
    const monthDob = dob.getMonth();
    const dateDob = dob.getDate();
    let age = {};
    let ageString = '';
    let yearString = '';
    let monthString = '';
    let dayString = '';
    let monthAge = 0;

    let yearAge = yearNow - yearDob,
      dateAge = 0;
    if (monthNow >= monthDob) monthAge = monthNow - monthDob;
    else {
      yearAge--;
      monthAge = 12 + monthNow - monthDob;
    }
    if (dateNow >= dateDob) {
      dateAge = dateNow - dateDob;
    } else {
      monthAge--;
      dateAge = 31 + dateNow - dateDob;
      if (monthAge < 0) {
        monthAge = 11;
        yearAge--;
      }
    }
    age = { years: yearAge, months: monthAge, days: dateAge };
    if (age.years > 1) yearString = 'years';
    else yearString = 'year';
    if (age.months > 1) monthString = 'months';
    else monthString = 'month';
    if (age.days > 1) dayString = 'days';
    else dayString = 'day';

    if (age.years > 0 && age.months > 0 && age.days > 0)
      ageString =
        age.years +
        yearString +
        ' ' +
        age.months +
        monthString +
        ' ' +
        age.days +
        dayString;
    else if (age.years === 0 && age.months === 0 && age.days > 0)
      ageString = age.days + dayString;
    else if (age.years > 0 && age.months === 0 && age.days === 0)
      ageString = age.years + yearString;
    else if (age.years > 0 && age.months > 0 && age.days === 0)
      ageString = age.years + yearString + ' ' + age.months + monthString;
    else if (age.years === 0 && age.months > 0 && age.days > 0)
      ageString = age.months + monthString + ' ' + age.days + dayString;
    else if (age.years > 0 && age.months === 0 && age.days > 0)
      ageString = age.years + yearString + ' ' + age.days + dayString;
    else if (age.years === 0 && age.months > 0 && age.days === 0)
      ageString = age.months + monthString;
    return ageString;
  },
  getDay: (date) => {
    if (!date) {
      return '';
    }
    
    const day = '';
    return day;
  },
};

export default Constants;
